# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_ble
    shield: re-gret rgbled_adapter
  - board: raytac_mdbt50q_rx
    shield: cradio_dongle
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_rp2040
    shield: tern
  - board: nice_nano_v2
    shield: egret
  - board: nice_nano_v2
    shield: cygnus34_left
  - board: nice_nano_v2
    shield: cygnus34_right
